#
# Travis Project Descriptor
#
# See http://about.travis-ci.org/docs/user/build-configuration/
#

# build matrix
language: python
python:
    - "2.7"
    - "2.6"
    - "3.3"
    - "pypy"
matrix:
    allow_failures:
        - python: "3.3"
        - python: "pypy"

# command to install dependencies
install: 
    - "pip install -r requirements.txt --use-mirrors"

# command to run tests
script: paver travis_ci

